// Uptime Cairn — probe protocol, assignment synchronisation.
//
// Full set, then deltas, then periodic reconciliation against a digest. This is
// deliberately the same diff-plus-reconcile pattern ADR-004 chose for the
// browser (ADR-005 decision 11) — one idea in the codebase, not two.
//
// See docs/probe/protocol.md §5 for the state machine, the digest definition,
// and what a probe does when the two sides disagree.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cairn/probe/v1/assignment.proto

package probev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One monitor, as a probe sees it. The probe knows nothing else about it: not
// its name, not its group, not its notification channels, not its current
// up/down state, not how many times it has failed in a row. The control plane
// owns all of that (decision 1).
type Assignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv7, 16 raw bytes. Unique within a session; monitor identity inside a
	// multi-session probe is (session, monitor_id) and never monitor_id alone,
	// because two control planes may legitimately issue the same UUID
	// (decision 3).
	MonitorId []byte `protobuf:"bytes,1,opt,name=monitor_id,json=monitorId,proto3" json:"monitor_id,omitempty"`
	// monitors.type. A probe that does not recognise the string rejects the
	// assignment (Rejection.REASON_UNSUPPORTED_TYPE) rather than guessing.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// monitors.config, verbatim — the same JSON the data model already stores
	// (§11.1), carried as opaque bytes.
	//
	// This is the highest-leverage line in the protocol (decision 6): adding a
	// monitor type is one Checker implementation, one registry entry, and a
	// config schema in the OpenAPI spec. It never changes this file, never bumps
	// the protocol version, and never invalidates a deployed probe.
	//
	// The cost, stated so nobody is surprised by it: the wire boundary enforces
	// nothing. A probe can be handed a config it cannot parse, and the answer is
	// to make that loud and immediate — see AssignmentRejection, and note that
	// validation happens at assignment time, not check time.
	//
	// It carries secrets. Everything in data model §12 that belongs to this
	// monitor is here in plaintext, decrypted by the control plane. Assignments
	// are never written to disk, never logged, and redacted from every error path
	// (decision 15).
	Config []byte `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	// Scheduling, promoted out of config because the scheduler needs them without
	// parsing type-specific JSON. All from the monitors table; the control plane
	// is authoritative for every one of them.
	IntervalSeconds uint32 `protobuf:"varint,4,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	TimeoutSeconds  uint32 `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Retries the probe performs itself, at retry_interval_seconds. Each attempt
	// is one Result, which is what heartbeats.attempt anticipates. The probe
	// stops at retries+1 attempts and never decides what the failures mean —
	// consecutive_failures and the state transition are control-plane work.
	Retries              uint32 `protobuf:"varint,6,opt,name=retries,proto3" json:"retries,omitempty"`
	RetryIntervalSeconds uint32 `protobuf:"varint,7,opt,name=retry_interval_seconds,json=retryIntervalSeconds,proto3" json:"retry_interval_seconds,omitempty"`
	// Inverts up and down after assertions are applied. Never inverts unknown or
	// skipped: those are statements about the probe, and an operator asking to
	// invert a monitor did not ask to invert their probe's health.
	UpsideDown bool `protobuf:"varint,8,opt,name=upside_down,json=upsideDown,proto3" json:"upside_down,omitempty"`
	// Opaque, changes whenever config or any scheduling field above changes.
	// Compared by equality only — never parsed, never ordered. It is half of the
	// reconciliation digest and the signal to re-validate a config.
	ConfigVersion string `protobuf:"bytes,9,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_cairn_probe_v1_assignment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_assignment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_assignment_proto_rawDescGZIP(), []int{0}
}

func (x *Assignment) GetMonitorId() []byte {
	if x != nil {
		return x.MonitorId
	}
	return nil
}

func (x *Assignment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Assignment) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Assignment) GetIntervalSeconds() uint32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *Assignment) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Assignment) GetRetries() uint32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *Assignment) GetRetryIntervalSeconds() uint32 {
	if x != nil {
		return x.RetryIntervalSeconds
	}
	return 0
}

func (x *Assignment) GetUpsideDown() bool {
	if x != nil {
		return x.UpsideDown
	}
	return false
}

func (x *Assignment) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

type WatchAssignmentsRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ProbeId []byte                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	// Empty on first connect, or whenever the probe has no assignments it trusts.
	// Otherwise the last set_version the probe fully applied.
	KnownSetVersion string `protobuf:"bytes,2,opt,name=known_set_version,json=knownSetVersion,proto3" json:"known_set_version,omitempty"`
	// The probe's digest over its own current set (protocol.md §5.3). Lets the
	// control plane answer a resumption with a delta when the versions match and
	// a full set when they do not, without a round trip to find out.
	KnownAssignmentDigest string `protobuf:"bytes,3,opt,name=known_assignment_digest,json=knownAssignmentDigest,proto3" json:"known_assignment_digest,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WatchAssignmentsRequest) Reset() {
	*x = WatchAssignmentsRequest{}
	mi := &file_cairn_probe_v1_assignment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAssignmentsRequest) ProtoMessage() {}

func (x *WatchAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_assignment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*WatchAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_assignment_proto_rawDescGZIP(), []int{1}
}

func (x *WatchAssignmentsRequest) GetProbeId() []byte {
	if x != nil {
		return x.ProbeId
	}
	return nil
}

func (x *WatchAssignmentsRequest) GetKnownSetVersion() string {
	if x != nil {
		return x.KnownSetVersion
	}
	return ""
}

func (x *WatchAssignmentsRequest) GetKnownAssignmentDigest() string {
	if x != nil {
		return x.KnownAssignmentDigest
	}
	return ""
}

type AssignmentUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*AssignmentUpdate_Set
	//	*AssignmentUpdate_Delta
	//	*AssignmentUpdate_Reconcile
	Update        isAssignmentUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignmentUpdate) Reset() {
	*x = AssignmentUpdate{}
	mi := &file_cairn_probe_v1_assignment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentUpdate) ProtoMessage() {}

func (x *AssignmentUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_assignment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentUpdate.ProtoReflect.Descriptor instead.
func (*AssignmentUpdate) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_assignment_proto_rawDescGZIP(), []int{2}
}

func (x *AssignmentUpdate) GetUpdate() isAssignmentUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *AssignmentUpdate) GetSet() *AssignmentSet {
	if x != nil {
		if x, ok := x.Update.(*AssignmentUpdate_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *AssignmentUpdate) GetDelta() *AssignmentDelta {
	if x != nil {
		if x, ok := x.Update.(*AssignmentUpdate_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *AssignmentUpdate) GetReconcile() *Reconcile {
	if x != nil {
		if x, ok := x.Update.(*AssignmentUpdate_Reconcile); ok {
			return x.Reconcile
		}
	}
	return nil
}

type isAssignmentUpdate_Update interface {
	isAssignmentUpdate_Update()
}

type AssignmentUpdate_Set struct {
	Set *AssignmentSet `protobuf:"bytes,1,opt,name=set,proto3,oneof"`
}

type AssignmentUpdate_Delta struct {
	Delta *AssignmentDelta `protobuf:"bytes,2,opt,name=delta,proto3,oneof"`
}

type AssignmentUpdate_Reconcile struct {
	Reconcile *Reconcile `protobuf:"bytes,3,opt,name=reconcile,proto3,oneof"`
}

func (*AssignmentUpdate_Set) isAssignmentUpdate_Update() {}

func (*AssignmentUpdate_Delta) isAssignmentUpdate_Update() {}

func (*AssignmentUpdate_Reconcile) isAssignmentUpdate_Update() {}

// The full set, chunked. gRPC's default 4 MiB receive limit is smaller than a
// 5,000-monitor set with ~1 KB of config each, so chunking is required rather
// than defensive: the probe accumulates chunks sharing a set_version and swaps
// its assignment table atomically when it sees final = true. A stream that
// drops mid-set is discarded, not half-applied.
type AssignmentSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetVersion    string                 `protobuf:"bytes,1,opt,name=set_version,json=setVersion,proto3" json:"set_version,omitempty"`
	Assignments   []*Assignment          `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty"`
	Final         bool                   `protobuf:"varint,3,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignmentSet) Reset() {
	*x = AssignmentSet{}
	mi := &file_cairn_probe_v1_assignment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentSet) ProtoMessage() {}

func (x *AssignmentSet) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_assignment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentSet.ProtoReflect.Descriptor instead.
func (*AssignmentSet) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_assignment_proto_rawDescGZIP(), []int{3}
}

func (x *AssignmentSet) GetSetVersion() string {
	if x != nil {
		return x.SetVersion
	}
	return ""
}

func (x *AssignmentSet) GetAssignments() []*Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *AssignmentSet) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

// Steady state. Sent as monitors are created, edited, paused, or reassigned.
type AssignmentDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version the probe holds *after* applying this delta.
	SetVersion        string        `protobuf:"bytes,1,opt,name=set_version,json=setVersion,proto3" json:"set_version,omitempty"`
	Added             []*Assignment `protobuf:"bytes,2,rep,name=added,proto3" json:"added,omitempty"`
	Updated           []*Assignment `protobuf:"bytes,3,rep,name=updated,proto3" json:"updated,omitempty"`
	RemovedMonitorIds [][]byte      `protobuf:"bytes,4,rep,name=removed_monitor_ids,json=removedMonitorIds,proto3" json:"removed_monitor_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AssignmentDelta) Reset() {
	*x = AssignmentDelta{}
	mi := &file_cairn_probe_v1_assignment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentDelta) ProtoMessage() {}

func (x *AssignmentDelta) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_assignment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentDelta.ProtoReflect.Descriptor instead.
func (*AssignmentDelta) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_assignment_proto_rawDescGZIP(), []int{4}
}

func (x *AssignmentDelta) GetSetVersion() string {
	if x != nil {
		return x.SetVersion
	}
	return ""
}

func (x *AssignmentDelta) GetAdded() []*Assignment {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *AssignmentDelta) GetUpdated() []*Assignment {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *AssignmentDelta) GetRemovedMonitorIds() [][]byte {
	if x != nil {
		return x.RemovedMonitorIds
	}
	return nil
}

// Periodic re-anchor, ~15 minutes. A resend of the full set at this cadence is
// unaffordable (~5 MB × every probe × every 15 min) and unnecessary: the probe
// compares digests and only asks for a full set when they differ. Same "if in
// doubt, re-fetch" rule ADR-004's membership signal uses.
type Reconcile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SetVersion       string                 `protobuf:"bytes,1,opt,name=set_version,json=setVersion,proto3" json:"set_version,omitempty"`
	AssignmentDigest string                 `protobuf:"bytes,2,opt,name=assignment_digest,json=assignmentDigest,proto3" json:"assignment_digest,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Reconcile) Reset() {
	*x = Reconcile{}
	mi := &file_cairn_probe_v1_assignment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reconcile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reconcile) ProtoMessage() {}

func (x *Reconcile) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_assignment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reconcile.ProtoReflect.Descriptor instead.
func (*Reconcile) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_assignment_proto_rawDescGZIP(), []int{5}
}

func (x *Reconcile) GetSetVersion() string {
	if x != nil {
		return x.SetVersion
	}
	return ""
}

func (x *Reconcile) GetAssignmentDigest() string {
	if x != nil {
		return x.AssignmentDigest
	}
	return ""
}

var File_cairn_probe_v1_assignment_proto protoreflect.FileDescriptor

const file_cairn_probe_v1_assignment_proto_rawDesc = "" +
	"\n" +
	"\x1fcairn/probe/v1/assignment.proto\x12\x0ecairn.probe.v1\"\xc3\x02\n" +
	"\n" +
	"Assignment\x12\x1d\n" +
	"\n" +
	"monitor_id\x18\x01 \x01(\fR\tmonitorId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06config\x18\x03 \x01(\fR\x06config\x12)\n" +
	"\x10interval_seconds\x18\x04 \x01(\rR\x0fintervalSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\rR\x0etimeoutSeconds\x12\x18\n" +
	"\aretries\x18\x06 \x01(\rR\aretries\x124\n" +
	"\x16retry_interval_seconds\x18\a \x01(\rR\x14retryIntervalSeconds\x12\x1f\n" +
	"\vupside_down\x18\b \x01(\bR\n" +
	"upsideDown\x12%\n" +
	"\x0econfig_version\x18\t \x01(\tR\rconfigVersion\"\x98\x01\n" +
	"\x17WatchAssignmentsRequest\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\fR\aprobeId\x12*\n" +
	"\x11known_set_version\x18\x02 \x01(\tR\x0fknownSetVersion\x126\n" +
	"\x17known_assignment_digest\x18\x03 \x01(\tR\x15knownAssignmentDigest\"\xc3\x01\n" +
	"\x10AssignmentUpdate\x121\n" +
	"\x03set\x18\x01 \x01(\v2\x1d.cairn.probe.v1.AssignmentSetH\x00R\x03set\x127\n" +
	"\x05delta\x18\x02 \x01(\v2\x1f.cairn.probe.v1.AssignmentDeltaH\x00R\x05delta\x129\n" +
	"\treconcile\x18\x03 \x01(\v2\x19.cairn.probe.v1.ReconcileH\x00R\treconcileB\b\n" +
	"\x06update\"\x84\x01\n" +
	"\rAssignmentSet\x12\x1f\n" +
	"\vset_version\x18\x01 \x01(\tR\n" +
	"setVersion\x12<\n" +
	"\vassignments\x18\x02 \x03(\v2\x1a.cairn.probe.v1.AssignmentR\vassignments\x12\x14\n" +
	"\x05final\x18\x03 \x01(\bR\x05final\"\xca\x01\n" +
	"\x0fAssignmentDelta\x12\x1f\n" +
	"\vset_version\x18\x01 \x01(\tR\n" +
	"setVersion\x120\n" +
	"\x05added\x18\x02 \x03(\v2\x1a.cairn.probe.v1.AssignmentR\x05added\x124\n" +
	"\aupdated\x18\x03 \x03(\v2\x1a.cairn.probe.v1.AssignmentR\aupdated\x12.\n" +
	"\x13removed_monitor_ids\x18\x04 \x03(\fR\x11removedMonitorIds\"Y\n" +
	"\tReconcile\x12\x1f\n" +
	"\vset_version\x18\x01 \x01(\tR\n" +
	"setVersion\x12+\n" +
	"\x11assignment_digest\x18\x02 \x01(\tR\x10assignmentDigestBBZ@github.com/webloomlabs/uptime-cairn/proto/cairn/probe/v1;probev1b\x06proto3"

var (
	file_cairn_probe_v1_assignment_proto_rawDescOnce sync.Once
	file_cairn_probe_v1_assignment_proto_rawDescData []byte
)

func file_cairn_probe_v1_assignment_proto_rawDescGZIP() []byte {
	file_cairn_probe_v1_assignment_proto_rawDescOnce.Do(func() {
		file_cairn_probe_v1_assignment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cairn_probe_v1_assignment_proto_rawDesc), len(file_cairn_probe_v1_assignment_proto_rawDesc)))
	})
	return file_cairn_probe_v1_assignment_proto_rawDescData
}

var file_cairn_probe_v1_assignment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cairn_probe_v1_assignment_proto_goTypes = []any{
	(*Assignment)(nil),              // 0: cairn.probe.v1.Assignment
	(*WatchAssignmentsRequest)(nil), // 1: cairn.probe.v1.WatchAssignmentsRequest
	(*AssignmentUpdate)(nil),        // 2: cairn.probe.v1.AssignmentUpdate
	(*AssignmentSet)(nil),           // 3: cairn.probe.v1.AssignmentSet
	(*AssignmentDelta)(nil),         // 4: cairn.probe.v1.AssignmentDelta
	(*Reconcile)(nil),               // 5: cairn.probe.v1.Reconcile
}
var file_cairn_probe_v1_assignment_proto_depIdxs = []int32{
	3, // 0: cairn.probe.v1.AssignmentUpdate.set:type_name -> cairn.probe.v1.AssignmentSet
	4, // 1: cairn.probe.v1.AssignmentUpdate.delta:type_name -> cairn.probe.v1.AssignmentDelta
	5, // 2: cairn.probe.v1.AssignmentUpdate.reconcile:type_name -> cairn.probe.v1.Reconcile
	0, // 3: cairn.probe.v1.AssignmentSet.assignments:type_name -> cairn.probe.v1.Assignment
	0, // 4: cairn.probe.v1.AssignmentDelta.added:type_name -> cairn.probe.v1.Assignment
	0, // 5: cairn.probe.v1.AssignmentDelta.updated:type_name -> cairn.probe.v1.Assignment
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cairn_probe_v1_assignment_proto_init() }
func file_cairn_probe_v1_assignment_proto_init() {
	if File_cairn_probe_v1_assignment_proto != nil {
		return
	}
	file_cairn_probe_v1_assignment_proto_msgTypes[2].OneofWrappers = []any{
		(*AssignmentUpdate_Set)(nil),
		(*AssignmentUpdate_Delta)(nil),
		(*AssignmentUpdate_Reconcile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cairn_probe_v1_assignment_proto_rawDesc), len(file_cairn_probe_v1_assignment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cairn_probe_v1_assignment_proto_goTypes,
		DependencyIndexes: file_cairn_probe_v1_assignment_proto_depIdxs,
		MessageInfos:      file_cairn_probe_v1_assignment_proto_msgTypes,
	}.Build()
	File_cairn_probe_v1_assignment_proto = out.File
	file_cairn_probe_v1_assignment_proto_goTypes = nil
	file_cairn_probe_v1_assignment_proto_depIdxs = nil
}
