// Uptime Cairn — probe protocol, service and session lifecycle.
//
// Binding documents. Where this file and one of them disagree, they win:
//   ADR-001  docs/adr/001-probe-and-control-plane-split.md   the split itself
//   ADR-005  docs/adr/005-probe-architecture.md              the sixteen decisions
//   semantics docs/probe/protocol.md                         what the bytes mean
//
// The .proto is the smaller half of the deliverable. Everything a third party
// needs that a message definition cannot express — retry, backoff, ordering,
// idempotency, what a probe must never do — is in docs/probe/protocol.md, and
// an implementation written from these files alone will be wrong in ways that
// only show up during an outage.
//
// Compatibility (ADR-005 decision 7, probe plan §4.12): additive only. Field
// numbers are never reused, never renumbered, and a field's meaning never
// changes. Anything breaking is package cairn.probe.v2, and v1 keeps working
// for the deprecation window in docs/api/README.md. Feature differences within
// v1 are handled by capability negotiation, never by version gating.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cairn/probe/v1/probe_service.proto

package probev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProbeService_Enrol_FullMethodName            = "/cairn.probe.v1.ProbeService/Enrol"
	ProbeService_IssueToken_FullMethodName       = "/cairn.probe.v1.ProbeService/IssueToken"
	ProbeService_Register_FullMethodName         = "/cairn.probe.v1.ProbeService/Register"
	ProbeService_WatchAssignments_FullMethodName = "/cairn.probe.v1.ProbeService/WatchAssignments"
	ProbeService_StreamResults_FullMethodName    = "/cairn.probe.v1.ProbeService/StreamResults"
)

// ProbeServiceClient is the client API for ProbeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The whole probe-facing surface. Five RPCs, all dialled outbound by the probe;
// the control plane never connects to a probe and a probe never listens
// (ADR-001). "Push" from the control plane means a frame written on a stream
// the probe already opened, which is why every control-plane→probe action takes
// effect on next connect rather than synchronously (ADR-005 decision 10).
type ProbeServiceClient interface {
	// One-time exchange of an enrolment token for a long-lived credential. The
	// only unauthenticated RPC, called once per control plane at first boot and
	// never in solo mode.
	Enrol(ctx context.Context, in *EnrolRequest, opts ...grpc.CallOption) (*EnrolResponse, error)
	// Exchange the long-lived credential for a short-lived access token. Called
	// on connect and again before expiry. This is what makes revocation take
	// effect within one token lifetime without operating a CA (decision 8).
	IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error)
	// Declare capabilities, capacity, and versions. Must succeed before
	// WatchAssignments or StreamResults; both fail FAILED_PRECONDITION otherwise.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Long-lived server stream: full assignment set, then deltas, then periodic
	// reconciliation against a digest (decision 11).
	WatchAssignments(ctx context.Context, in *WatchAssignmentsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AssignmentUpdate], error)
	// Long-lived bidirectional stream: batched results up, acknowledged
	// high-water marks down (decision 12). Self-metrics ride along on the same
	// stream because a probe has no inbound port to scrape (probe plan §4.13).
	StreamResults(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ResultBatch, ResultAck], error)
}

type probeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProbeServiceClient(cc grpc.ClientConnInterface) ProbeServiceClient {
	return &probeServiceClient{cc}
}

func (c *probeServiceClient) Enrol(ctx context.Context, in *EnrolRequest, opts ...grpc.CallOption) (*EnrolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrolResponse)
	err := c.cc.Invoke(ctx, ProbeService_Enrol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeServiceClient) IssueToken(ctx context.Context, in *IssueTokenRequest, opts ...grpc.CallOption) (*IssueTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueTokenResponse)
	err := c.cc.Invoke(ctx, ProbeService_IssueToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ProbeService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *probeServiceClient) WatchAssignments(ctx context.Context, in *WatchAssignmentsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AssignmentUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProbeService_ServiceDesc.Streams[0], ProbeService_WatchAssignments_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchAssignmentsRequest, AssignmentUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProbeService_WatchAssignmentsClient = grpc.ServerStreamingClient[AssignmentUpdate]

func (c *probeServiceClient) StreamResults(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ResultBatch, ResultAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProbeService_ServiceDesc.Streams[1], ProbeService_StreamResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResultBatch, ResultAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProbeService_StreamResultsClient = grpc.BidiStreamingClient[ResultBatch, ResultAck]

// ProbeServiceServer is the server API for ProbeService service.
// All implementations must embed UnimplementedProbeServiceServer
// for forward compatibility.
//
// The whole probe-facing surface. Five RPCs, all dialled outbound by the probe;
// the control plane never connects to a probe and a probe never listens
// (ADR-001). "Push" from the control plane means a frame written on a stream
// the probe already opened, which is why every control-plane→probe action takes
// effect on next connect rather than synchronously (ADR-005 decision 10).
type ProbeServiceServer interface {
	// One-time exchange of an enrolment token for a long-lived credential. The
	// only unauthenticated RPC, called once per control plane at first boot and
	// never in solo mode.
	Enrol(context.Context, *EnrolRequest) (*EnrolResponse, error)
	// Exchange the long-lived credential for a short-lived access token. Called
	// on connect and again before expiry. This is what makes revocation take
	// effect within one token lifetime without operating a CA (decision 8).
	IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error)
	// Declare capabilities, capacity, and versions. Must succeed before
	// WatchAssignments or StreamResults; both fail FAILED_PRECONDITION otherwise.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Long-lived server stream: full assignment set, then deltas, then periodic
	// reconciliation against a digest (decision 11).
	WatchAssignments(*WatchAssignmentsRequest, grpc.ServerStreamingServer[AssignmentUpdate]) error
	// Long-lived bidirectional stream: batched results up, acknowledged
	// high-water marks down (decision 12). Self-metrics ride along on the same
	// stream because a probe has no inbound port to scrape (probe plan §4.13).
	StreamResults(grpc.BidiStreamingServer[ResultBatch, ResultAck]) error
	mustEmbedUnimplementedProbeServiceServer()
}

// UnimplementedProbeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProbeServiceServer struct{}

func (UnimplementedProbeServiceServer) Enrol(context.Context, *EnrolRequest) (*EnrolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enrol not implemented")
}
func (UnimplementedProbeServiceServer) IssueToken(context.Context, *IssueTokenRequest) (*IssueTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueToken not implemented")
}
func (UnimplementedProbeServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedProbeServiceServer) WatchAssignments(*WatchAssignmentsRequest, grpc.ServerStreamingServer[AssignmentUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchAssignments not implemented")
}
func (UnimplementedProbeServiceServer) StreamResults(grpc.BidiStreamingServer[ResultBatch, ResultAck]) error {
	return status.Error(codes.Unimplemented, "method StreamResults not implemented")
}
func (UnimplementedProbeServiceServer) mustEmbedUnimplementedProbeServiceServer() {}
func (UnimplementedProbeServiceServer) testEmbeddedByValue()                      {}

// UnsafeProbeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProbeServiceServer will
// result in compilation errors.
type UnsafeProbeServiceServer interface {
	mustEmbedUnimplementedProbeServiceServer()
}

func RegisterProbeServiceServer(s grpc.ServiceRegistrar, srv ProbeServiceServer) {
	// If the following call panics, it indicates UnimplementedProbeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProbeService_ServiceDesc, srv)
}

func _ProbeService_Enrol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServiceServer).Enrol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProbeService_Enrol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServiceServer).Enrol(ctx, req.(*EnrolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProbeService_IssueToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServiceServer).IssueToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProbeService_IssueToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServiceServer).IssueToken(ctx, req.(*IssueTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProbeService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProbeService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProbeService_WatchAssignments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchAssignmentsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProbeServiceServer).WatchAssignments(m, &grpc.GenericServerStream[WatchAssignmentsRequest, AssignmentUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProbeService_WatchAssignmentsServer = grpc.ServerStreamingServer[AssignmentUpdate]

func _ProbeService_StreamResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProbeServiceServer).StreamResults(&grpc.GenericServerStream[ResultBatch, ResultAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProbeService_StreamResultsServer = grpc.BidiStreamingServer[ResultBatch, ResultAck]

// ProbeService_ServiceDesc is the grpc.ServiceDesc for ProbeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProbeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cairn.probe.v1.ProbeService",
	HandlerType: (*ProbeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enrol",
			Handler:    _ProbeService_Enrol_Handler,
		},
		{
			MethodName: "IssueToken",
			Handler:    _ProbeService_IssueToken_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _ProbeService_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchAssignments",
			Handler:       _ProbeService_WatchAssignments_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamResults",
			Handler:       _ProbeService_StreamResults_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cairn/probe/v1/probe_service.proto",
}
