// Uptime Cairn — probe protocol, service and session lifecycle.
//
// Binding documents. Where this file and one of them disagree, they win:
//   ADR-001  docs/adr/001-probe-and-control-plane-split.md   the split itself
//   ADR-005  docs/adr/005-probe-architecture.md              the sixteen decisions
//   semantics docs/probe/protocol.md                         what the bytes mean
//
// The .proto is the smaller half of the deliverable. Everything a third party
// needs that a message definition cannot express — retry, backoff, ordering,
// idempotency, what a probe must never do — is in docs/probe/protocol.md, and
// an implementation written from these files alone will be wrong in ways that
// only show up during an outage.
//
// Compatibility (ADR-005 decision 7, probe plan §4.12): additive only. Field
// numbers are never reused, never renumbered, and a field's meaning never
// changes. Anything breaking is package cairn.probe.v2, and v1 keeps working
// for the deprecation window in docs/api/README.md. Feature differences within
// v1 are handled by capability negotiation, never by version gating.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cairn/probe/v1/probe_service.proto

package probev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Credential placement rule, stated once and applied throughout: a credential
// being *exchanged for another* is a message field, because it is the subject
// of the call. A credential *authorising* a call is `authorization: Bearer …`
// request metadata. So enrolment tokens and long-lived credentials appear in
// messages; access tokens never do.
type EnrolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Single-use, short-TTL, scoped to one org and one probe row. Hashed into
	// probes.token_hash by the control plane (decision 8).
	EnrolmentToken string `protobuf:"bytes,1,opt,name=enrolment_token,json=enrolmentToken,proto3" json:"enrolment_token,omitempty"`
	// Advisory. The probe row already carries the operator's chosen name; this is
	// what the probe host calls itself, useful when they disagree.
	RequestedName   string `protobuf:"bytes,2,opt,name=requested_name,json=requestedName,proto3" json:"requested_name,omitempty"`
	AgentVersion    string `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ProtocolVersion uint32 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Probe wall clock. Lets the control plane refuse an enrolment from a host
	// whose clock would poison the time series before it has sent anything.
	ProbeTimeUnixMicros int64 `protobuf:"varint,5,opt,name=probe_time_unix_micros,json=probeTimeUnixMicros,proto3" json:"probe_time_unix_micros,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnrolRequest) Reset() {
	*x = EnrolRequest{}
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrolRequest) ProtoMessage() {}

func (x *EnrolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrolRequest.ProtoReflect.Descriptor instead.
func (*EnrolRequest) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_probe_service_proto_rawDescGZIP(), []int{0}
}

func (x *EnrolRequest) GetEnrolmentToken() string {
	if x != nil {
		return x.EnrolmentToken
	}
	return ""
}

func (x *EnrolRequest) GetRequestedName() string {
	if x != nil {
		return x.RequestedName
	}
	return ""
}

func (x *EnrolRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrolRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *EnrolRequest) GetProbeTimeUnixMicros() int64 {
	if x != nil {
		return x.ProbeTimeUnixMicros
	}
	return 0
}

type EnrolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv7, 16 raw bytes — the probes.id this probe was pre-registered as.
	// Every UUID on this protocol is encoded this way; never a string.
	ProbeId []byte `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	// Long-lived, written to disk at 0600 and nothing else is (decision 9: the
	// credential is identity, not state). Opaque to the probe.
	Credential                    string `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	CredentialExpiresAtUnixMicros int64  `protobuf:"varint,3,opt,name=credential_expires_at_unix_micros,json=credentialExpiresAtUnixMicros,proto3" json:"credential_expires_at_unix_micros,omitempty"`
	ServerTimeUnixMicros          int64  `protobuf:"varint,4,opt,name=server_time_unix_micros,json=serverTimeUnixMicros,proto3" json:"server_time_unix_micros,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *EnrolResponse) Reset() {
	*x = EnrolResponse{}
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrolResponse) ProtoMessage() {}

func (x *EnrolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrolResponse.ProtoReflect.Descriptor instead.
func (*EnrolResponse) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_probe_service_proto_rawDescGZIP(), []int{1}
}

func (x *EnrolResponse) GetProbeId() []byte {
	if x != nil {
		return x.ProbeId
	}
	return nil
}

func (x *EnrolResponse) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *EnrolResponse) GetCredentialExpiresAtUnixMicros() int64 {
	if x != nil {
		return x.CredentialExpiresAtUnixMicros
	}
	return 0
}

func (x *EnrolResponse) GetServerTimeUnixMicros() int64 {
	if x != nil {
		return x.ServerTimeUnixMicros
	}
	return 0
}

type IssueTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    string                 `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_probe_service_proto_rawDescGZIP(), []int{2}
}

func (x *IssueTokenRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type IssueTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Presented as `authorization: Bearer <access_token>` on every subsequent
	// call, including a re-registration. Minutes, not days.
	AccessToken                    string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessTokenExpiresAtUnixMicros int64  `protobuf:"varint,2,opt,name=access_token_expires_at_unix_micros,json=accessTokenExpiresAtUnixMicros,proto3" json:"access_token_expires_at_unix_micros,omitempty"`
	// Set only when the control plane is rotating this probe's credential. The
	// probe writes it atomically and uses it from the next exchange onward; the
	// previous credential stays valid for the grace period in the semantics doc,
	// so a rotation that races a crash cannot lock a probe out (probe plan
	// §4.9(e)).
	RotatedCredential                    string `protobuf:"bytes,3,opt,name=rotated_credential,json=rotatedCredential,proto3" json:"rotated_credential,omitempty"`
	RotatedCredentialExpiresAtUnixMicros int64  `protobuf:"varint,4,opt,name=rotated_credential_expires_at_unix_micros,json=rotatedCredentialExpiresAtUnixMicros,proto3" json:"rotated_credential_expires_at_unix_micros,omitempty"`
	ServerTimeUnixMicros                 int64  `protobuf:"varint,5,opt,name=server_time_unix_micros,json=serverTimeUnixMicros,proto3" json:"server_time_unix_micros,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *IssueTokenResponse) Reset() {
	*x = IssueTokenResponse{}
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenResponse) ProtoMessage() {}

func (x *IssueTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_probe_service_proto_rawDescGZIP(), []int{3}
}

func (x *IssueTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *IssueTokenResponse) GetAccessTokenExpiresAtUnixMicros() int64 {
	if x != nil {
		return x.AccessTokenExpiresAtUnixMicros
	}
	return 0
}

func (x *IssueTokenResponse) GetRotatedCredential() string {
	if x != nil {
		return x.RotatedCredential
	}
	return ""
}

func (x *IssueTokenResponse) GetRotatedCredentialExpiresAtUnixMicros() int64 {
	if x != nil {
		return x.RotatedCredentialExpiresAtUnixMicros
	}
	return 0
}

func (x *IssueTokenResponse) GetServerTimeUnixMicros() int64 {
	if x != nil {
		return x.ServerTimeUnixMicros
	}
	return 0
}

// What a probe can actually do, declared per check type. This is the
// compatibility mechanism (decision 7): a probe that does not advertise a type
// is never assigned one, so an old probe against a newer control plane is a
// capability difference rather than a version error.
type Capability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches monitors.type in the data model and MonitorType in the OpenAPI
	// spec: http, tcp, icmp, dns, tls_expiry, domain_expiry, docker, grpc.
	// `push` never appears here — it is evaluated by the control plane and is
	// never assigned to a probe at all (decision 6, probe plan §5).
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The checker's version, not the agent's. Lets a control plane withhold a
	// monitor whose config uses a feature an older checker would silently ignore.
	// 0 when unavailable.
	Version   uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Available bool   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	// Required when available is false, and it is user-facing: this is the string
	// that turns "ICMP does not work in this container" from an error repeated
	// 250 times a second into a fact the control plane holds before a single
	// check runs. "raw sockets unavailable: no CAP_NET_RAW" is the shape.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_probe_service_proto_rawDescGZIP(), []int{4}
}

func (x *Capability) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Capability) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Capability) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Capability) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RegisterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion    string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Region          string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Capabilities    []*Capability          `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Capacity, so the control plane can decline an assignment and tell the user
	// "probe at capacity" rather than assigning work that will be shed (probe
	// plan §4.5). Both are the probe's own configured ceilings.
	MaxConcurrentChecks uint32 `protobuf:"varint,6,opt,name=max_concurrent_checks,json=maxConcurrentChecks,proto3" json:"max_concurrent_checks,omitempty"`
	MaxChecksPerSecond  uint32 `protobuf:"varint,7,opt,name=max_checks_per_second,json=maxChecksPerSecond,proto3" json:"max_checks_per_second,omitempty"`
	ProbeTimeUnixMicros int64  `protobuf:"varint,8,opt,name=probe_time_unix_micros,json=probeTimeUnixMicros,proto3" json:"probe_time_unix_micros,omitempty"`
	// "linux/arm64". Operator-facing; the Pi user is a stated persona and a fleet
	// list that cannot show architecture cannot show why one probe is slow.
	Platform      string `protobuf:"bytes,9,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_probe_service_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetMaxConcurrentChecks() uint32 {
	if x != nil {
		return x.MaxConcurrentChecks
	}
	return 0
}

func (x *RegisterRequest) GetMaxChecksPerSecond() uint32 {
	if x != nil {
		return x.MaxChecksPerSecond
	}
	return 0
}

func (x *RegisterRequest) GetProbeTimeUnixMicros() int64 {
	if x != nil {
		return x.ProbeTimeUnixMicros
	}
	return 0
}

func (x *RegisterRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authoritative. Solo mode never enrols, so this is where the embedded probe
	// row's id comes from (decision 14).
	ProbeId              []byte `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	ServerTimeUnixMicros int64  `protobuf:"varint,2,opt,name=server_time_unix_micros,json=serverTimeUnixMicros,proto3" json:"server_time_unix_micros,omitempty"`
	// The control plane's own protocol version. Equal major or the call would
	// have failed FAILED_PRECONDITION.
	ProtocolVersion uint32 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Server-driven tuning. Every value has a probe-side default (semantics doc
	// §9), and 0 means "keep your default" — so a control plane that sets none of
	// them is valid, and a fleet can be retuned without a probe release.
	HealthIntervalSeconds     uint32 `protobuf:"varint,4,opt,name=health_interval_seconds,json=healthIntervalSeconds,proto3" json:"health_interval_seconds,omitempty"`
	ReconcileIntervalSeconds  uint32 `protobuf:"varint,5,opt,name=reconcile_interval_seconds,json=reconcileIntervalSeconds,proto3" json:"reconcile_interval_seconds,omitempty"`
	ResultBatchMaxResults     uint32 `protobuf:"varint,6,opt,name=result_batch_max_results,json=resultBatchMaxResults,proto3" json:"result_batch_max_results,omitempty"`
	ResultFlushIntervalMillis uint32 `protobuf:"varint,7,opt,name=result_flush_interval_millis,json=resultFlushIntervalMillis,proto3" json:"result_flush_interval_millis,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cairn_probe_v1_probe_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_cairn_probe_v1_probe_service_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetProbeId() []byte {
	if x != nil {
		return x.ProbeId
	}
	return nil
}

func (x *RegisterResponse) GetServerTimeUnixMicros() int64 {
	if x != nil {
		return x.ServerTimeUnixMicros
	}
	return 0
}

func (x *RegisterResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RegisterResponse) GetHealthIntervalSeconds() uint32 {
	if x != nil {
		return x.HealthIntervalSeconds
	}
	return 0
}

func (x *RegisterResponse) GetReconcileIntervalSeconds() uint32 {
	if x != nil {
		return x.ReconcileIntervalSeconds
	}
	return 0
}

func (x *RegisterResponse) GetResultBatchMaxResults() uint32 {
	if x != nil {
		return x.ResultBatchMaxResults
	}
	return 0
}

func (x *RegisterResponse) GetResultFlushIntervalMillis() uint32 {
	if x != nil {
		return x.ResultFlushIntervalMillis
	}
	return 0
}

var File_cairn_probe_v1_probe_service_proto protoreflect.FileDescriptor

const file_cairn_probe_v1_probe_service_proto_rawDesc = "" +
	"\n" +
	"\"cairn/probe/v1/probe_service.proto\x12\x0ecairn.probe.v1\x1a\x1fcairn/probe/v1/assignment.proto\x1a\x1bcairn/probe/v1/result.proto\"\xe3\x01\n" +
	"\fEnrolRequest\x12'\n" +
	"\x0fenrolment_token\x18\x01 \x01(\tR\x0eenrolmentToken\x12%\n" +
	"\x0erequested_name\x18\x02 \x01(\tR\rrequestedName\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\rR\x0fprotocolVersion\x123\n" +
	"\x16probe_time_unix_micros\x18\x05 \x01(\x03R\x13probeTimeUnixMicros\"\xcb\x01\n" +
	"\rEnrolResponse\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\fR\aprobeId\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\tR\n" +
	"credential\x12H\n" +
	"!credential_expires_at_unix_micros\x18\x03 \x01(\x03R\x1dcredentialExpiresAtUnixMicros\x125\n" +
	"\x17server_time_unix_micros\x18\x04 \x01(\x03R\x14serverTimeUnixMicros\"3\n" +
	"\x11IssueTokenRequest\x12\x1e\n" +
	"\n" +
	"credential\x18\x01 \x01(\tR\n" +
	"credential\"\xc3\x02\n" +
	"\x12IssueTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12K\n" +
	"#access_token_expires_at_unix_micros\x18\x02 \x01(\x03R\x1eaccessTokenExpiresAtUnixMicros\x12-\n" +
	"\x12rotated_credential\x18\x03 \x01(\tR\x11rotatedCredential\x12W\n" +
	")rotated_credential_expires_at_unix_micros\x18\x04 \x01(\x03R$rotatedCredentialExpiresAtUnixMicros\x125\n" +
	"\x17server_time_unix_micros\x18\x05 \x01(\x03R\x14serverTimeUnixMicros\"p\n" +
	"\n" +
	"Capability\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x85\x03\n" +
	"\x0fRegisterRequest\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12>\n" +
	"\fcapabilities\x18\x05 \x03(\v2\x1a.cairn.probe.v1.CapabilityR\fcapabilities\x122\n" +
	"\x15max_concurrent_checks\x18\x06 \x01(\rR\x13maxConcurrentChecks\x121\n" +
	"\x15max_checks_per_second\x18\a \x01(\rR\x12maxChecksPerSecond\x123\n" +
	"\x16probe_time_unix_micros\x18\b \x01(\x03R\x13probeTimeUnixMicros\x12\x1a\n" +
	"\bplatform\x18\t \x01(\tR\bplatform\"\xff\x02\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\fR\aprobeId\x125\n" +
	"\x17server_time_unix_micros\x18\x02 \x01(\x03R\x14serverTimeUnixMicros\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\rR\x0fprotocolVersion\x126\n" +
	"\x17health_interval_seconds\x18\x04 \x01(\rR\x15healthIntervalSeconds\x12<\n" +
	"\x1areconcile_interval_seconds\x18\x05 \x01(\rR\x18reconcileIntervalSeconds\x127\n" +
	"\x18result_batch_max_results\x18\x06 \x01(\rR\x15resultBatchMaxResults\x12?\n" +
	"\x1cresult_flush_interval_millis\x18\a \x01(\rR\x19resultFlushIntervalMillis2\xa6\x03\n" +
	"\fProbeService\x12D\n" +
	"\x05Enrol\x12\x1c.cairn.probe.v1.EnrolRequest\x1a\x1d.cairn.probe.v1.EnrolResponse\x12S\n" +
	"\n" +
	"IssueToken\x12!.cairn.probe.v1.IssueTokenRequest\x1a\".cairn.probe.v1.IssueTokenResponse\x12M\n" +
	"\bRegister\x12\x1f.cairn.probe.v1.RegisterRequest\x1a .cairn.probe.v1.RegisterResponse\x12_\n" +
	"\x10WatchAssignments\x12'.cairn.probe.v1.WatchAssignmentsRequest\x1a .cairn.probe.v1.AssignmentUpdate0\x01\x12K\n" +
	"\rStreamResults\x12\x1b.cairn.probe.v1.ResultBatch\x1a\x19.cairn.probe.v1.ResultAck(\x010\x01BBZ@github.com/webloomlabs/uptime-cairn/proto/cairn/probe/v1;probev1b\x06proto3"

var (
	file_cairn_probe_v1_probe_service_proto_rawDescOnce sync.Once
	file_cairn_probe_v1_probe_service_proto_rawDescData []byte
)

func file_cairn_probe_v1_probe_service_proto_rawDescGZIP() []byte {
	file_cairn_probe_v1_probe_service_proto_rawDescOnce.Do(func() {
		file_cairn_probe_v1_probe_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cairn_probe_v1_probe_service_proto_rawDesc), len(file_cairn_probe_v1_probe_service_proto_rawDesc)))
	})
	return file_cairn_probe_v1_probe_service_proto_rawDescData
}

var file_cairn_probe_v1_probe_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cairn_probe_v1_probe_service_proto_goTypes = []any{
	(*EnrolRequest)(nil),            // 0: cairn.probe.v1.EnrolRequest
	(*EnrolResponse)(nil),           // 1: cairn.probe.v1.EnrolResponse
	(*IssueTokenRequest)(nil),       // 2: cairn.probe.v1.IssueTokenRequest
	(*IssueTokenResponse)(nil),      // 3: cairn.probe.v1.IssueTokenResponse
	(*Capability)(nil),              // 4: cairn.probe.v1.Capability
	(*RegisterRequest)(nil),         // 5: cairn.probe.v1.RegisterRequest
	(*RegisterResponse)(nil),        // 6: cairn.probe.v1.RegisterResponse
	(*WatchAssignmentsRequest)(nil), // 7: cairn.probe.v1.WatchAssignmentsRequest
	(*ResultBatch)(nil),             // 8: cairn.probe.v1.ResultBatch
	(*AssignmentUpdate)(nil),        // 9: cairn.probe.v1.AssignmentUpdate
	(*ResultAck)(nil),               // 10: cairn.probe.v1.ResultAck
}
var file_cairn_probe_v1_probe_service_proto_depIdxs = []int32{
	4,  // 0: cairn.probe.v1.RegisterRequest.capabilities:type_name -> cairn.probe.v1.Capability
	0,  // 1: cairn.probe.v1.ProbeService.Enrol:input_type -> cairn.probe.v1.EnrolRequest
	2,  // 2: cairn.probe.v1.ProbeService.IssueToken:input_type -> cairn.probe.v1.IssueTokenRequest
	5,  // 3: cairn.probe.v1.ProbeService.Register:input_type -> cairn.probe.v1.RegisterRequest
	7,  // 4: cairn.probe.v1.ProbeService.WatchAssignments:input_type -> cairn.probe.v1.WatchAssignmentsRequest
	8,  // 5: cairn.probe.v1.ProbeService.StreamResults:input_type -> cairn.probe.v1.ResultBatch
	1,  // 6: cairn.probe.v1.ProbeService.Enrol:output_type -> cairn.probe.v1.EnrolResponse
	3,  // 7: cairn.probe.v1.ProbeService.IssueToken:output_type -> cairn.probe.v1.IssueTokenResponse
	6,  // 8: cairn.probe.v1.ProbeService.Register:output_type -> cairn.probe.v1.RegisterResponse
	9,  // 9: cairn.probe.v1.ProbeService.WatchAssignments:output_type -> cairn.probe.v1.AssignmentUpdate
	10, // 10: cairn.probe.v1.ProbeService.StreamResults:output_type -> cairn.probe.v1.ResultAck
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_cairn_probe_v1_probe_service_proto_init() }
func file_cairn_probe_v1_probe_service_proto_init() {
	if File_cairn_probe_v1_probe_service_proto != nil {
		return
	}
	file_cairn_probe_v1_assignment_proto_init()
	file_cairn_probe_v1_result_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cairn_probe_v1_probe_service_proto_rawDesc), len(file_cairn_probe_v1_probe_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cairn_probe_v1_probe_service_proto_goTypes,
		DependencyIndexes: file_cairn_probe_v1_probe_service_proto_depIdxs,
		MessageInfos:      file_cairn_probe_v1_probe_service_proto_msgTypes,
	}.Build()
	File_cairn_probe_v1_probe_service_proto = out.File
	file_cairn_probe_v1_probe_service_proto_goTypes = nil
	file_cairn_probe_v1_probe_service_proto_depIdxs = nil
}
